apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpddep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: httpdcont
          image: httpd
          ports:
            - containerPort: 8004
