apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
        - name: dep1
          image: nginx
          ports:
            - containerPort: 5005


