apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdep
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: myapp 
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginxcont12
          image: nginx
          ports:
            - containerPort: 8003
