apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginxdep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginxcont
          image: nginx
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8082
  selector:
    app: myapp

