apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: myapp-lb
  template:
    metadata:
      labels:
        app: myapp-lb
    spec:
      containers:
        - name: ngcont
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ngsvc
  labels:
    app: myapp-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myapp-lb
