apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx-app
  template:
    metadata:
      labels:
        app: mynginx-app
    spec:
      containers:
        - name: nginxcont
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: nginxsvc
  labels:
    app: mynginx-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mynginx-app
