apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdep1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: ngcont
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ngsvc
  labels:
    app: myapp
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: myapp

